name: FreeProxy

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PySocks
      - name: Print installed packages
        run: pip freeze
      - name: Check Python version
        run: python --version
      - name: Check Python path
        run: python -c "import sys; print(sys.path)"
      - run: curl -s -L ${{secrets.UPDATER}} -o updater.py
      - run: python updater.py
      - name: Commit files
        run: |
          git config --local user.email ${{ secrets.GIT_EMAIL }}
          git config --local user.name ${{ secrets.GIT_NAME }}
          git commit -am "Updated Proxies"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
        env:
          CI: true
